// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskRuntime.Persistence;

#nullable disable

namespace TaskRuntime.Persistence.SqlServerMigrations.Migrations
{
    [DbContext(typeof(TaskRuntimeDbContext))]
    [Migration("20260703032633_AddTaskRunPayloadVersionAndDeduplication")]
    partial class AddTaskRunPayloadVersionAndDeduplication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tasks")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Tasks.Infrastructure.TaskControlMessageState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeliveredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EnqueuedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Status", "EnqueuedAtUtc");

                    b.ToTable("task_control_messages", "tasks");
                });

            modelBuilder.Entity("Shared.Tasks.Infrastructure.TaskRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CancellationRequestedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CancellationRequestedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeduplicationKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset?>("LastHeartbeatAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LeasedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NodeId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(262144)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PayloadVersion")
                        .HasColumnType("int");

                    b.Property<string>("ProgressMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int?>("ProgressPercent")
                        .HasColumnType("int");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ScheduledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("WorkerGroup")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleName", "TaskName");

                    b.HasIndex("ModuleName", "TaskName", "TenantId", "DeduplicationKey", "Status");

                    b.HasIndex("WorkerGroup", "Status", "ScheduledAtUtc", "NextAttemptAtUtc", "LockedUntilUtc");

                    b.ToTable("task_runs", "tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
