// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notifications.Persistence;

#nullable disable

namespace Notifications.Persistence.SqlServerMigrations.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20260706063948_MakeMessageScopeOptional")]
    partial class MakeMessageScopeOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Notifications.Domain.Aggregates.NotificationBroadcast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("Audience");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PayloadJson");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("Severity");

                    b.Property<long>("StreamSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StreamSequence"));

                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Audience", "TenantId", "OccurredAtUtc");

                    b.HasIndex("Audience", "TenantId", "StreamSequence");

                    b.ToTable("notification_broadcasts", "notifications");
                });

            modelBuilder.Entity("Notifications.Domain.Aggregates.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PayloadJson");

                    b.Property<DateTimeOffset?>("ReadAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UserId");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("Severity");

                    b.Property<long>("StreamSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StreamSequence"));

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "StreamSequence");

                    b.HasIndex("TenantId", "Recipient", "OccurredAtUtc");

                    b.HasIndex("TenantId", "Recipient", "ReadAtUtc");

                    b.HasIndex("TenantId", "Recipient", "StreamSequence");

                    b.ToTable("user_notifications", "notifications");
                });

            modelBuilder.Entity("Notifications.Domain.Entities.NotificationBroadcastRead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BroadcastId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ReadAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("RecipientId");

                    b.Property<string>("RecipientKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("RecipientKind");

                    b.Property<string>("RecipientScope")
                        .IsRequired()
                        .HasMaxLength(135)
                        .HasColumnType("nvarchar(135)");

                    b.HasKey("Id");

                    b.HasIndex("BroadcastId", "RecipientScope", "RecipientKind", "Recipient")
                        .IsUnique();

                    b.HasIndex("RecipientScope", "RecipientKind", "Recipient", "BroadcastId");

                    b.ToTable("notification_broadcast_reads", "notifications");
                });

            modelBuilder.Entity("Shared.Messaging.Infrastructure.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Handler")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessingStartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("TenantId");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id", "Handler");

                    b.HasIndex("Handler", "Status");

                    b.ToTable("inbox_messages", "notifications");
                });

            modelBuilder.Entity("Notifications.Domain.Aggregates.NotificationBroadcast", b =>
                {
                    b.OwnsOne("Notifications.Domain.ValueObjects.NotificationContent", "Content", b1 =>
                        {
                            b1.Property<Guid>("NotificationBroadcastId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Body")
                                .HasMaxLength(4096)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Body");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Title");

                            b1.HasKey("NotificationBroadcastId");

                            b1.ToTable("notification_broadcasts", "notifications");

                            b1.WithOwner()
                                .HasForeignKey("NotificationBroadcastId");
                        });

                    b.OwnsOne("Notifications.Domain.ValueObjects.NotificationSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("NotificationBroadcastId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Module")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("Module");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("Name");

                            b1.Property<int>("Version")
                                .HasColumnType("int")
                                .HasColumnName("Version");

                            b1.HasKey("NotificationBroadcastId");

                            b1.HasIndex("Module", "Name", "Version");

                            b1.ToTable("notification_broadcasts", "notifications");

                            b1.WithOwner()
                                .HasForeignKey("NotificationBroadcastId");
                        });

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("Notifications.Domain.Aggregates.UserNotification", b =>
                {
                    b.OwnsOne("Notifications.Domain.ValueObjects.NotificationContent", "Content", b1 =>
                        {
                            b1.Property<Guid>("UserNotificationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Body")
                                .HasMaxLength(4096)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Body");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Title");

                            b1.HasKey("UserNotificationId");

                            b1.ToTable("user_notifications", "notifications");

                            b1.WithOwner()
                                .HasForeignKey("UserNotificationId");
                        });

                    b.OwnsOne("Notifications.Domain.ValueObjects.NotificationSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("UserNotificationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Module")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("Module");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("Name");

                            b1.Property<int>("Version")
                                .HasColumnType("int")
                                .HasColumnName("Version");

                            b1.HasKey("UserNotificationId");

                            b1.HasIndex("Module", "Name", "Version");

                            b1.ToTable("user_notifications", "notifications");

                            b1.WithOwner()
                                .HasForeignKey("UserNotificationId");
                        });

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Source")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
